### ISSUE TITLE
Team Ram-Rod Project 3

### ISSUE THREAD

**Issue by jball23** [ga-dc/wdi9-project3-gallery#6]
Link to repo(Angular): https://github.com/jball23/brokers-open
Link to repo(Rails): https://github.com/jball23/brokers-open-rails
Link to deployed app: http://jball23.github.io/brokers-open/brokers-open-angular/#/listings

Things you'd like specific feedback on:

**Comment by RobertAKARobin** [comment]
# Project 3 Evaluation

Inline code comments:
    - https://github.com/jball23/brokers-open-rails/pull/1/files
    - https://github.com/jball23/brokers-open/pull/7/files

## Back-end Technology

**2: Performing**

> Includes 2 models

It's a bit confusing that the Users are actually Agents. Also, creating listings doesn't work. I've included a solution for this in my code comments.

## Front-end Technology

**2: Performing**

> Front-end makes appropriate use of Angular controllers and states with ui-router. Includes 1 custom directive

## Code Quality

**2: Performing**

> Code is well-formatted, well-named, and contains few style / quality issues

For the most part, your code looks great! There are a few minor inconsistencies with code formatting and indentation, and the Google Maps code gets pretty gnarly. I appreciate the GIF and the ¯_(ツ)_/¯, but still...

## Deployment and Functionality

**2: Performing**

> Application contains no major errors, is deployed correctly, and contains a custom Heroku app name appropriate for the app.

## Planning / Process / Submission

**1: Progressing**

> App is submitted, with basic evidence of planning. Documentation exists, but lacks common areas such as setup instructions, description of application functionality and link to deployed application.

## Comments

Nice app, guys! Good job on keeping it simple. You did everything pretty by-the-book, and then branched out by incorporating the Google Maps API.  I was wondering what CSS framework you used, and was pleasantly surprised to see that it was both hand-written and minimal.
